# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: HTTP Prompt - An interactive command-line HTTP client
description: > # this means to ignore newlines until "baseurl:"
  HTTP Prompt is an interactive command-line HTTP client featuring autocomplete
  and syntax highlighting, built on HTTPie and prompt_toolkit.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://http-prompt.com" # the base hostname & protocol for your site, e.g. http://example.com
docs_url: "http://docs.http-prompt.com"
docs_baseurl: "http://docs.http-prompt.com/en/latest"
github_url: "https://github.com/eliangcs/http-prompt"
gitter_url: "https://gitter.im/eliangcs/http-prompt"
producthunt_url: "https://www.producthunt.com/posts/http-prompt"
license_url: "https://github.com/eliangcs/http-prompt/blob/master/LICENSE"
comm_license_url: "https://github.com/eliangcs/http-prompt/blob/master/COMM-LICENSE"
creator_github_url: "https://github.com/eliangcs"
creator_name: "Chang-Hung Liang"

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
